[package]
name = "y2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
itertools = "0.10"
regex = "1.5"
# livin on the edge
clap = { version = "3.0.0-rc.5", features=["derive"]}
